name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_NUMBER: 0.0.${{github.run_number}}${{ github.ref != 'refs/heads/main' && '-pre' || '' }}

jobs:

  build-docker-image:
    name: "Build docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          file: Dockerfile
          tags:
            mattrichardson/arduino-ota-updater:${{env.BUILD_NUMBER}}
          push: true
  
  create-octopus-release:
    name: "Create Octopus release"
    runs-on: ubuntu-latest
    needs: [build-docker-image]
    steps:
      - name: Login to Octopus Deploy 🐙
        uses: OctopusDeploy/login@v1
        with: 
          server: https://matt-richardson.octopus.app
          service_account_id: 6281c06f-8f5a-4328-83e5-7da4510d4b49
      - name: Create Octopus Release 🐙
        uses: OctopusDeploy/create-release-action@v3
        with:
          project: arduino-ota-updater
          release_number: ${{env.BUILD_NUMBER}}
          package_version: ${{env.BUILD_NUMBER}}