name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_NUMBER: 0.0.${{github.run_number}}${{ github.ref != 'refs/heads/main' && '-pre' || '' }}

jobs:

  build-docker-image:
    name: "Build docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          file: Dockerfile
          tags:
            mattrichardson/arduino-ota-updater:${{env.BUILD_NUMBER}}
          push: true
  
  create-octopus-release:
    name: "Create Octopus release"
    runs-on: ubuntu-latest
    needs: [build-docker-image]
    steps:
      - name: "Create a release on Octopus"
        uses: docker://octopusdeploy/octo
        env:
          OCTOPUS_CLI_SERVER: ${{ secrets.OCTOPUS_SERVER }}
          OCTOPUS_CLI_API_KEY: ${{ secrets.OCTOPUS_APIKEY }}
        with:
          args: create-release --project=arduino-ota-updater --version=${{env.BUILD_NUMBER}} --packageVersion=${{env.BUILD_NUMBER}}